export const Z = {
  base: 0,
  content: 1,
  ambientGlow: 2,
  grain: 5,
  scrollVelocity: 8,
  lavaTypography: 10,
  moldCast: 11,
  cncStory: 12,
  marquee: 15,
  dotNav: 20,
  header: 50,
  mobileMenu: 60,
  cursor: 90,
  pageTransition: 95,
  preloader: 100,
} as const;

export type ZLayer = keyof typeof Z;

/** Section stacking order — ascending so each section covers the previous */
export const SECTION_Z = {
  hero:                    1,
  lavaTypography:          2,
  moldCast:                3,
  cncStory:                4,
  nexus:                   5,
  wave:                    6,
  whyUs:                   7,
  nexusToHwwGlow:          8,
  howWeWork:               9,
  hwwToCertGlow:           10,
  certifications:          11,
  videoScroll:             12,
  videoToServicesGlow:     13,
  services:                14,
  glowLine:                14,
  industries:              15,
  industriesToProjectGlow: 16,
  projectShowcase:         17,
  materialMorph:           18,
  materials:               19,
  whyToCapGlow:            20,
  capabilities:            21,
  testimonials:            22,
  faqBlog:                 23,
  faqToCtaGlow:            24,
  finalCta:                25,
} as const;
