-- ============================================================
-- MAS TECHNİC - SUPABASE TAM KURULUM BETİĞİ
-- Referans & Yedek Dokümantasyonu
-- Tarih: 2026-02-25 (Canlı DB ile doğrulanmış versiyon)
-- ============================================================
-- Bu dosya mevcut canlı veritabanının birebir kopyasıdır.
-- Sıfırdan kurulum veya felaket kurtarma senaryoları için kullanılabilir.
-- Tüm komutlar idempotent (tekrar çalıştırılabilir) yazılmıştır.
-- ============================================================


-- ************************************************************
-- BÖLÜM 1: ENUM VE FONKSİYONLAR
-- ************************************************************

-- 1.1 Rol Enum Tanımı
DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('admin', 'staff', 'production', 'quality');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- 1.2 Rol Kontrol Fonksiyonu (SECURITY DEFINER)
-- Belirli bir kullanıcının belirli bir role sahip olup olmadığını kontrol eder.
-- RLS politikalarında recursive sorgu sorununu önlemek için SECURITY DEFINER kullanılır.
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;


-- 1.3 Personel Kontrol Fonksiyonu (SECURITY DEFINER)
-- Kullanıcının user_roles tablosunda herhangi bir kaydı olup olmadığını kontrol eder.
CREATE OR REPLACE FUNCTION public.is_staff(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id
  )
$$;


-- 1.4 updated_at Otomatik Güncelleme Trigger Fonksiyonu
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- ************************************************************
-- BÖLÜM 2: TABLO OLUŞTURMA (13 Tablo)
-- ************************************************************

-- 2.1 user_roles - Kullanıcı Rolleri
CREATE TABLE IF NOT EXISTS public.user_roles (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role       app_role NOT NULL,
  UNIQUE (user_id, role)
);

-- 2.2 customers - Müşteriler
CREATE TABLE IF NOT EXISTS public.customers (
  id         integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       text,
  company    text,
  email      text,
  phone      text,
  city       text,
  balance    numeric,
  last_order date,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- 2.3 rfqs - Teklif Talepleri
CREATE TABLE IF NOT EXISTS public.rfqs (
  id         text PRIMARY KEY,
  customer   text,
  company    text,
  email      text,
  phone      text,
  service    text,
  material   text,
  quantity   integer,
  notes      text,
  files      text[],
  status     text,
  date       date,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- 2.4 orders - Siparişler
CREATE TABLE IF NOT EXISTS public.orders (
  id         text PRIMARY KEY,
  customer   text,
  part_name  text,
  quantity   integer,
  status     text,
  progress   integer,
  order_date date,
  deadline   date,
  rfq_ref    text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- 2.5 wbs - İş Kırılım Yapısı
CREATE TABLE IF NOT EXISTS public.wbs (
  id           text PRIMARY KEY,
  customer     text,
  part_name    text,
  machine      text,
  current_step integer,
  total_qty    integer,
  status       text,
  deadline     date,
  created_at   timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- 2.6 meetings - Toplantılar
CREATE TABLE IF NOT EXISTS public.meetings (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text NOT NULL,
  email        text NOT NULL,
  phone        text,
  company      text,
  topic        text NOT NULL,
  meeting_date date NOT NULL,
  meeting_time text NOT NULL,
  notes        text,
  status       text NOT NULL DEFAULT 'pending',
  user_id      uuid DEFAULT auth.uid() REFERENCES auth.users(id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- 2.7 issues - Sorunlar / NCR
CREATE TABLE IF NOT EXISTS public.issues (
  id         text PRIMARY KEY,
  job        text,
  machine    text,
  category   text,
  severity   text,
  status     text,
  detail     text,
  resolution text,
  date       date,
  cost       numeric,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- 2.8 financial_documents - Finansal Belgeler
CREATE TABLE IF NOT EXISTS public.financial_documents (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  doc_type               text NOT NULL DEFAULT 'fatura',
  doc_number             text,
  title                  text,
  vendor                 text,
  category               text,
  amount                 numeric DEFAULT 0,
  vat_rate               numeric DEFAULT 18,
  vat_amount             numeric DEFAULT 0,
  total_amount           numeric DEFAULT 0,
  currency               text DEFAULT 'TRY',
  doc_date               date DEFAULT CURRENT_DATE,
  due_date               date,
  payment_status         text DEFAULT 'ödenmedi',
  status                 text DEFAULT 'beklemede',
  source                 text DEFAULT 'manuel',
  notes                  text,
  tags                   text[],
  file_urls              text[],
  ai_category_suggestion text,
  ai_summary             text,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

-- 2.9 machine_health - Makine Sağlığı
CREATE TABLE IF NOT EXISTS public.machine_health (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name             text NOT NULL,
  status           text DEFAULT 'normal',
  spindle_hours    integer DEFAULT 0,
  oil_level        integer DEFAULT 100,
  filter_life      integer DEFAULT 100,
  next_maintenance integer DEFAULT 5000,
  created_at       timestamptz NOT NULL DEFAULT now()
);

-- 2.10 maintenance_logs - Bakım Kayıtları
CREATE TABLE IF NOT EXISTS public.maintenance_logs (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machine    text NOT NULL,
  type       text NOT NULL DEFAULT 'Periyodik',
  date       date NOT NULL DEFAULT CURRENT_DATE,
  detail     text,
  technician text,
  duration   text,
  cost       numeric DEFAULT 0,
  status     text DEFAULT 'Tamamlandı',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2.11 tool_inventory - Takım Envanteri
CREATE TABLE IF NOT EXISTS public.tool_inventory (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code       text NOT NULL,
  name       text NOT NULL,
  category   text,
  stock      integer DEFAULT 0,
  min_stock  integer DEFAULT 5,
  unit_cost  numeric DEFAULT 0,
  supplier   text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2.12 raw_materials - Hammaddeler
CREATE TABLE IF NOT EXISTS public.raw_materials (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code       text NOT NULL,
  name       text NOT NULL,
  spec       text,
  unit       text DEFAULT 'adet',
  stock      integer DEFAULT 0,
  unit_cost  numeric DEFAULT 0,
  waste_rate numeric DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2.13 faq_analytics - SSS Analitiği
CREATE TABLE IF NOT EXISTS public.faq_analytics (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  question   text,
  query      text,
  category   text,
  created_at timestamptz NOT NULL DEFAULT now()
);


-- ************************************************************
-- BÖLÜM 3: FOREIGN KEY İLİŞKİLERİ
-- ************************************************************

-- orders.rfq_ref -> rfqs.id
DO $$ BEGIN
  ALTER TABLE public.orders
    ADD CONSTRAINT orders_rfq_ref_fkey
    FOREIGN KEY (rfq_ref) REFERENCES public.rfqs(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Not: user_roles.user_id -> auth.users(id) ve meetings.user_id -> auth.users(id)
-- ilişkileri tablo tanımlarında inline olarak belirtilmiştir (Bölüm 2).


-- ************************************************************
-- BÖLÜM 4: CHECK KISITLAMALARI
-- ************************************************************

-- ── 4.1 customers tablosu ──
DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_name_length CHECK ((name IS NULL) OR (length(name) <= 200));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_company_length CHECK ((company IS NULL) OR (length(company) <= 200));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_city_length CHECK ((city IS NULL) OR (length(city) <= 100));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_phone_length CHECK ((phone IS NULL) OR (length(phone) <= 30));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_email_length CHECK ((email IS NULL) OR (length(email) <= 255));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.customers ADD CONSTRAINT check_customer_email_format CHECK ((email IS NULL) OR (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 4.2 meetings tablosu ──
DO $$ BEGIN
  ALTER TABLE public.meetings ADD CONSTRAINT check_name_length CHECK (length(name) >= 2 AND length(name) <= 100);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.meetings ADD CONSTRAINT check_email_length CHECK (length(email) <= 255);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.meetings ADD CONSTRAINT check_phone_length CHECK ((phone IS NULL) OR (length(phone) <= 20));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.meetings ADD CONSTRAINT check_topic_length CHECK (length(topic) >= 1 AND length(topic) <= 200);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.meetings ADD CONSTRAINT check_notes_length CHECK ((notes IS NULL) OR (length(notes) <= 1000));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 4.3 rfqs tablosu ──
DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_customer_length CHECK ((customer IS NULL) OR (length(customer) <= 200));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_company_length CHECK ((company IS NULL) OR (length(company) <= 200));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_email_length CHECK ((email IS NULL) OR (length(email) <= 255));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_service_length CHECK ((service IS NULL) OR (length(service) <= 100));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_material_length CHECK ((material IS NULL) OR (length(material) <= 100));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_notes_length CHECK ((notes IS NULL) OR (length(notes) <= 2000));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.rfqs ADD CONSTRAINT check_rfq_quantity_positive CHECK ((quantity IS NULL) OR (quantity > 0));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 4.4 faq_analytics tablosu ──
DO $$ BEGIN
  ALTER TABLE public.faq_analytics ADD CONSTRAINT faq_analytics_event_type_check CHECK (event_type = ANY (ARRAY['search', 'click']));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- ************************************************************
-- BÖLÜM 5: ROW LEVEL SECURITY ETKİNLEŞTİRME
-- ************************************************************

ALTER TABLE public.user_roles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rfqs                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wbs                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issues              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machine_health      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_logs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tool_inventory      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raw_materials       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faq_analytics       ENABLE ROW LEVEL SECURITY;


-- ************************************************************
-- BÖLÜM 6: RLS POLİTİKALARI (Tablo Bazında Gruplu)
-- ************************************************************
-- Not: Tüm politikalar PERMISSIVE (Supabase varsayılanı) olarak tanımlanmıştır.
-- Canlı veritabanından doğrulanmıştır.

-- ────────────────────────────────────────
-- 6.1 user_roles
-- ────────────────────────────────────────
CREATE POLICY "Admins can read all roles"  ON public.user_roles FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Users can read own roles"   ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins can insert roles"    ON public.user_roles FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update roles"    ON public.user_roles FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete roles"    ON public.user_roles FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.2 customers
-- ────────────────────────────────────────
CREATE POLICY "Staff can read customers"   ON public.customers FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert customers" ON public.customers FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update customers" ON public.customers FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete customers" ON public.customers FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.3 rfqs
-- ────────────────────────────────────────
-- Anonim kullanıcılar teklif gönderebilir (sınırlı kontrol ile)
CREATE POLICY "Anyone can submit RFQ"     ON public.rfqs FOR INSERT WITH CHECK (id IS NOT NULL AND length(id) > 0);
CREATE POLICY "Staff can read rfqs"       ON public.rfqs FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can update rfqs"     ON public.rfqs FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete rfqs"    ON public.rfqs FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.4 orders
-- ────────────────────────────────────────
CREATE POLICY "Staff can read orders"     ON public.orders FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert orders"   ON public.orders FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update orders"   ON public.orders FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete orders"  ON public.orders FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.5 wbs
-- ────────────────────────────────────────
CREATE POLICY "Staff can read wbs"        ON public.wbs FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert wbs"      ON public.wbs FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update wbs"      ON public.wbs FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete wbs"     ON public.wbs FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.6 meetings
-- ────────────────────────────────────────
-- Sahiplik bazlı: Kullanıcı sadece kendi toplantılarını görebilir
CREATE POLICY "meetings_select_policy"    ON public.meetings FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "meetings_insert_policy"    ON public.meetings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "meetings_update_policy"    ON public.meetings FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "meetings_delete_policy"    ON public.meetings FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- ────────────────────────────────────────
-- 6.7 issues
-- ────────────────────────────────────────
CREATE POLICY "Staff can read issues"     ON public.issues FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert issues"   ON public.issues FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update issues"   ON public.issues FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete issues"  ON public.issues FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.8 financial_documents (Sadece Admin)
-- ────────────────────────────────────────
CREATE POLICY "Admins can read financial_documents"   ON public.financial_documents FOR SELECT TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can insert financial_documents" ON public.financial_documents FOR INSERT TO authenticated WITH CHECK (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can update financial_documents" ON public.financial_documents FOR UPDATE TO authenticated USING (has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins can delete financial_documents" ON public.financial_documents FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.9 machine_health
-- ────────────────────────────────────────
CREATE POLICY "Staff can read machine_health"   ON public.machine_health FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert machine_health" ON public.machine_health FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update machine_health" ON public.machine_health FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete machine_health" ON public.machine_health FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.10 maintenance_logs
-- ────────────────────────────────────────
CREATE POLICY "Staff can read maintenance_logs"   ON public.maintenance_logs FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert maintenance_logs" ON public.maintenance_logs FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update maintenance_logs" ON public.maintenance_logs FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete maintenance_logs" ON public.maintenance_logs FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.11 tool_inventory
-- ────────────────────────────────────────
CREATE POLICY "Staff can read tool_inventory"   ON public.tool_inventory FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert tool_inventory" ON public.tool_inventory FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update tool_inventory" ON public.tool_inventory FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete tool_inventory" ON public.tool_inventory FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.12 raw_materials
-- ────────────────────────────────────────
CREATE POLICY "Staff can read raw_materials"   ON public.raw_materials FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Staff can insert raw_materials" ON public.raw_materials FOR INSERT TO authenticated WITH CHECK (is_staff(auth.uid()));
CREATE POLICY "Staff can update raw_materials" ON public.raw_materials FOR UPDATE TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete raw_materials" ON public.raw_materials FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));

-- ────────────────────────────────────────
-- 6.13 faq_analytics
-- ────────────────────────────────────────
-- Anonim INSERT: event_type zorunlu, sadece 'search' veya 'click' değerleri kabul edilir
CREATE POLICY "Anyone can insert faq analytics" ON public.faq_analytics FOR INSERT WITH CHECK (event_type IS NOT NULL AND length(event_type) > 0);
CREATE POLICY "Staff can read faq analytics"    ON public.faq_analytics FOR SELECT TO authenticated USING (is_staff(auth.uid()));
CREATE POLICY "Admins can delete faq analytics" ON public.faq_analytics FOR DELETE TO authenticated USING (has_role(auth.uid(), 'admin'));
-- Not: faq_analytics tablosunda UPDATE politikası yoktur (tasarım gereği).


-- ************************************************************
-- BÖLÜM 7: TRİGGER BAĞLAMA
-- ************************************************************

-- financial_documents tablosunda updated_at otomatik güncelleme
DROP TRIGGER IF EXISTS set_updated_at ON public.financial_documents;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.financial_documents
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();


-- ************************************************************
-- BÖLÜM 8: STORAGE BUCKET TANIMLARI (Referans)
-- ************************************************************
-- Aşağıdaki bucket'lar Supabase Dashboard veya API ile oluşturulmalıdır.
-- SQL ile doğrudan oluşturulamaz, burada sadece referans olarak belirtilmiştir.
--
-- 1. finance-docs  (Private) - Finansal belge PDF/görselleri
-- 2. cad-uploads   (Private) - CAD dosya yüklemeleri (STEP, IGES, vb.)
--
-- Her iki bucket da PRIVATE olarak yapılandırılmıştır.
-- Erişim Supabase Auth + RLS üzerinden kontrol edilir.


-- ************************************************************
-- BÖLÜM 9: ADMİN KULLANICI ATAMA ÖRNEĞİ
-- ************************************************************
-- İlk admin kullanıcısını atamak için:
-- (Supabase Auth'a kayıt olduktan sonra auth.users tablosundan user_id alınır)
--
-- INSERT INTO public.user_roles (user_id, role)
-- VALUES ('BURAYA-AUTH-USER-UUID', 'admin');
--
-- Ek roller atamak için:
-- INSERT INTO public.user_roles (user_id, role)
-- VALUES ('BURAYA-AUTH-USER-UUID', 'staff');


-- ============================================================
-- DOSYA SONU
-- Toplam: 1 Enum, 3 Fonksiyon, 13 Tablo, ~48 RLS Politikası,
--         19 CHECK Kısıtlaması, 3 Foreign Key, 1 Trigger,
--         2 Storage Bucket (referans)
-- ============================================================
