// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdqiujpeewtyhtcqhdcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcWl1anBlZXd0eWh0Y3FoZGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NTY0ODAsImV4cCI6MjA4NjIzMjQ4MH0.njAezeA6ikarsELTNRsDHdUefPWhyxQ0kGNPuFk8zrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});